include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    flutter_style_todos: ignore
  exclude:
    - lib/firebase_options.dart
    - "**.freezed.dart"
    - "**.g.dart"
